### ISSUE TITLE
Option to not recover panics

### ISSUE THREAD

**Issue by calmh** [thejerf/suture#18]
Hi! This is something I'm considering and may implement, I just want to hear your thoughts on it first.

We use suture for running a bunch of internal services. We let services return when an intentional restart is required (reconfiguration) or when a fatal error happens, typically on the form of a `log.Println("Error: ..."); return` from the `Serve()` method. So far all good. In fact, since we do intentional restarts now and then we do not output the log info from suture by default, so the restarts are silent unless we ourselves printed an error and returned as above. Perhaps this is the wrong way to do it, but we do not want the log messages of failed and restarting services when the user just requested a reconfiguration.

The problem comes when a service makes a call into some other function or package where something bad happens and it panics. Generally speaking our services should never panic, but we have some cases guarded with things like `if ... { panic("bug: can't happen: ...") }` that can trigger when we *do* hit that bug, and wanted the backtrace to be able to narrow it down. Of course, with our setup described above this panic is silently swallowed and restarted so we'll never know.

I'd like suture to do what it does, but let panics panic. That is, a service failing softly by returning is managed and retried, but a panic should take down the entire process - something which triggers logging the panic to a file and potentially notifying people and so on in our environment.

The modification to suture is fairly trivial - a new boolean in the Spec, and checking that around the defer in runService. Is this something you would consider, or is it counter to the idea of suture?

**Comment by thejerf** [comment]
It is contrary to the spirit of suture, yeah, in the sense that suture can't really tell what's going on with panics.

If I am reading you correctly, which I'm not 100% sure about because I'm not at my best right now, my suggestion would be to make the Serve function:

    func (o *Object) Serve() {
        for {
            o.realServe()
        }
    }

A normal return from realServe will restart the service, and a panic will flow up as usual.

If you're _really_ pressed for space and can't afford the extra stack frame, you can also put a label at the beginning of the Serve function and `goto` it instead of returning. That's actually a theoretically justifiable use of goto because it's basically a hand-implemented tail-call, but it may make your fellow programmers look at you funny.

Oh, and, yes, it _is_ in the spirit of suture that services are free to restart themselves "normally" and the supervisor doesn't want or need to hear about that case.

**Comment by calmh** [comment]
Actually, that might indeed be better. Thanks for the advice.
