### ISSUE TITLE
Serve() should be able to indicate why it stopped abruptly

### ISSUE THREAD

**Issue by AudriusButkevicius** [thejerf/suture#22]
As it stands now, if a service stops abruptly, usually you won't get any explanation as to why it stopped unless the service itself decided to report it somehow. You can work around that by panic'ing instead of returning, in which case suture logs something useful, but that's a bit of a nuclear option.

It would be nice if Serve() was able to return an error, and suture would log that.
Obviously in the Stop() case you'd expect error to be nil.

**Comment by thejerf** [comment]
I am very cautious about putting anything into Suture that is easy to implement yourself. For instance, I know there's a fork of Suture out there that adds a Context to the services; my feeling is that if you want contexts in your services you should just go ahead and put it in the types; in my opinion suture doesn't really add much by trying to get in the middle of that transaction.

The other theory here is that if the service would return an "error", by the Go definition of error handling it is a non-critical or non-surprising failure that it ought to handle itself. It's the panics I'm trying to catch.

In this case, I'd suggest a wrapper:

    type ErroringService interface {
        Start() error
        Stop()
    }

    type ErroringServiceWrapper struct {
        ErroringService
    }

    func (esw *ErroringServiceWrapper) Serve() {
        for {
            err := esr.ErroringService.Start()
            if err == nil {
                return
            }
            // log error here as you desire
        }
    }

I'm just bashing this out here without testing, and you probably want to cut that name down. You can also write something like

    func AddES(s *suture.Supervisor, srv ErroringService) {
        s.Add(&ErroringServiceWrapper{svr})
    }

I did briefly consider declaring a callback you could use to wrap the service automatically but since the type here doesn't match, it would require something more substantial again (a new field for the callback and a new AddSomethingIHopeWillEndUpBeingAServiceAfterCallback(interface{}). Possibly with a nicer name.)

Leaving this open for a bit to encourage discussion and feedback.

**Comment by AudriusButkevicius** [comment]
I guess the annoyance comes from the fact that Suture already has all the APIs necessary to log failures, yet there is no way to tell it to log anything meaningful.

**Comment by lthibault** [comment]
@AudriusButkevicius https://github.com/thejerf/suture/pull/23 Should make it possible to log what you need.

**Comment by AudriusButkevicius** [comment]
Not really, that just allows tapping into the loggers, there still isn't a built-in way for services to report errors to suture, for it to print the error as it goes into the retry cycle.

**Comment by thejerf** [comment]
No, I think you understand what that PR brings.

It still seems to me the answer is to wrap your handler with what you want. I remain quite reluctant to put things into suture that you can implement yourself easily, because there's a never-ending supply of those.

Plus suture is going to give you an annoyingly generic log functionality if I did provide it. Lacking a common logging interface, it would be another logging method, or something hard-coded to a formatted string, or something else unpleasant. If you do it yourself you can integrate with a JSON-based logger and suture doesn't care. (That's part of the motivation behind the logging callbacks I have already in there. Normally you'd expect some sort of printf-type logger, but then if you want JSON logging or something you have to work even harder.)

**Comment by AudriusButkevicius** [comment]
I agree with that.
