### ISSUE TITLE
Question about receiving .Stop() on failed services

### ISSUE THREAD

**Issue by alexzorin** [thejerf/suture#38]
Hi Jerf,

Just want to say that I always enjoy your excellent comments on /r/golang.

I'm wondering whether you could help me understand what is going on in https://play.golang.org/p/hazi0wwnZGM.

My mental model is: the service has failed, `.Serve()` has exited. Why would the stopping supervisor then call `.Stop()` on a service which is already "stopped" (perhaps "failed and not yet started again" is more accurate)? 

I could maybe prevent the `.Stop()` timeout by making the exit channel buffered, but I fear that I have greatly misunderstood something conceptually.

Thanks!

**Comment by thejerf** [comment]
There's a [TOCTTOU](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) issue; if suture tries to do logic on whether the service is still running, then between the time it decides it is running and the time it chooses to issue the .Stop call, the service may have crashed. There's no way to synchronize on that any more than we already are, so suture has to simply write code based on its inability to know whether the goroutine has crashed or not.

The other direction is theoretically possible, since the supervisor does run in one goroutine and it could theoretically notice that the service is currently stopped, but I think it's a much more solid guarantee to say "A Supervisor will call your .Stop function once upon termination, and no more" rather than "A supervisor will call .Stop once, unless it looks like it's already crashed in which case it won't." Probably someone's using .Stop to do more logging or concretely close a resource or something and still wants it called even if the service is momentarily not running. I don't think I have anything major I've done but I think I've got some minor such things that depend on that in my code. (Or, at least, really hope .Stop is called even so; technically you can't count on .Stop getting called since os.Exit() will skip it.)

I think this does mean you generally want to write the stopping portion in a way that it can be called no matter what. I generally do this by closing a channel, which gets closed nowhere else, either by closing a channel belonging to the service or cancelling a context in my .Stop function.

However, what you've written still has a valid use case, where you want the service to acknowledge the stop command, so that you can _try_ to avoid half-doing something. I say _try_, because if a goroutine has frozen, there are no mechanisms in Go at all, for suture or anyone else to use, to know what's going on in that goroutine. Suture has a time out here simply because that is literally your only option. Even as a human being it would be your only option. You might decide to wait more or less time than suture, but sooner or later you'd have to manually kill it too. All you have is a best-effort here.

I'm closing this issue just so it doesn't sit around being open, but if you have more comments, please feel free to keep commenting, reopening the issue if necessary (I can't recall if github forbids comments on closed issues); I'm not trying to shut down conversation, just avoid having this end up being open for months. (& I also can't remember if you can re-open them; if not feel free to open a new one.)

**Comment by alexzorin** [comment]
>I generally do this by closing a channel, which gets closed nowhere else

D'oh. Some things are so obvious in hindsight. Apparently I use `close` much too rarely for it to come into my head.

>what you've written still has a valid use case, where you want the service to acknowledge the stop command, so that you can try to avoid half-doing something

FWIW this was mainly about making ensuring that `BadStopLogger` only records "real" failures to stop (when `Serve()` never exits), so it remains useful when I then export it as a Prometheus metric.

Thanks!
