### ISSUE TITLE
Handling fatal errors

### ISSUE THREAD

**Issue by imsodin** [thejerf/suture#39]
At Syncthing we are using suture to manage various components of the application as services/sub-supervisors. For some of those there's expected reasons they might trigger the entire application to shut down, for others there are circumstances where just restarting the single component/service isn't viable (e.g. db corruption). To tackle that there has to be some way to signal a fatal error, prompting all services to be stopped. I made a prototype wrapping suture such that the serve signature becomes `Serve() error` and there's a `FatalErr` type, such that if the returned error is of that type its supervisor stops all other services and its own `Serve` method returns with the same error, thus taking the entire tree down: https://github.com/syncthing/syncthing/pull/6849. Naturally it would be even nicer if such a mechanism or something completely different, achieving the same purpose, would be part of suture itself. At the same time it's clear that the current proposal of changing `Serve` is a rather fundamental change.

What are your thoughts on the problem and/or whether a similar or different mechanism could fit into suture?

**Comment by thejerf** [comment]
I think the idea is good, and the only real question is how it gets presented to existing users.

I wouldn't consider revving a new major version off the table, but it would be nice to take a moment to think about whether or not this could be accomplished with something less serious.

My initial gut thought is to add 

```type XService interface {
     Serve() error
}```

and then add a .AddX(...) to the Supervisor. Under the hood all existing services can be wrapped to be turned into XServices that always return nil.

However, I am having a heck of a time coming up with exactly what word that X is. A lot of the initial thoughts are inaccurate; CrashableService isn't right, _all_ services are "crashable", etc.

Maybe "AddErroring"? Then we can document the errors coming out of it.

**Comment by thejerf** [comment]
Hmmm... I need it to be something other than Serve, because supervisors will still need to be .Add()able under the old interface, even if we upgrade them if they have the new interface, and we can only have one Serve.

I have to admit I'm tempted to roll a new major version. The cruft this one thing adds isn't necessarily that big a deal but it starts adding up when you accept it... and the compiler will catch everything if the Serve interface is modified.

**Comment by imsodin** [comment]
I have been thinking about how to extend suture before trying the wrapping and surmised I'd have to duplicate must types/interfaces, which I didn't consider viable. Nice to hear that you consider it worthwhile enough to potentially cut a new major version. And are even already prototyping. Let me know if i can help.

**Comment by thejerf** [comment]
I did come up with a way to extend it without a backwards-incompatible change, but I think it's too dangerous. You could add a .ReasonStopped method as an optional implementation on a Service that returns an error, but you have to carefully manage the results to make sure you clear the error after it's been returned once... it's very easy to misuse.

I think I'm going to roll a major version; gotta look up how to do that correctly, I really wasn't _all_ that careful last time (since it was still API-compatible).

**Comment by thejerf** [comment]
This is my current plan:

* Roll a new v4 for this.
  * Directly & fully support go modules as well.
* Change Serve() to also return an error. Work this error into the logs somehow.
* A new error TerminateSupervisor which will terminate the supervisor if returned. This is propagated by default, and a wrapper for the Supervisor that will stop that propagation will be provided.
* A new error TerminateService will allow a service to voluntarily terminate and not be restarted.
* Both of these will be checked for via errors.Is if the current version of Go supports that; otherwise they will be checked via direct equality. (I'm not sure what syncthing targets. If it's older than Go 1.9 please let me know.)
* A wrapper to take an old service and wrap it to always return nil, to make upgrading easier.

I expect this to take a few days. It'll start out on a branch called "v4" (not yet pushed) before I merge it into master, and you can try it out then. This is my first attempt to "properly" roll a new major version of anything via go modules, so bear with me if this take a couple of tries to get right.

Sound good?

**Comment by imsodin** [comment]
Sounds very good, thanks!  

One question: `TerminateSupervisor` and `TerminateService` are errors (respectively error types), right? What's the reason for separate ones? In my understanding a supervisor is also just a service to its supervisor, i.e. I'd expect it to return the same kind of error that start the termination.

**Comment by thejerf** [comment]
If you have a supervisor tree, but you have a supervisor that wants to die but _not_ bring down its parent, it needs something it can return to its supervisor to indicate that it is going down, but not the whole tree.

Otherwise the parent sees it goes down and tries to restart it. Parent needs some indication that it shouldn't restart the service.

It sounds like you intend to take down the entire program, so this use case doesn't appeal to you. That behavior will be the default, unless you specifically wrap the sub-supervisors to act otherwise, so it should be good.

I am not sure if they will be types or errors; I will try to make them just errors, because that's simpler, but if they have to carry parameters I will have to make them types. I'll discover that as I go.

**Comment by imsodin** [comment]
Ah I misunderstood your initial description: I thought they did the same thing but one is for services the other for supervisors. However what they are is "I had a fatal error and don't want to be restarted" vs "I had a fatal error and want everyone else to terminate as well".

**Comment by AudriusButkevicius** [comment]
Another thing we have internally in syncthing (we're wrapping a ton of suture for our own ease of use), which given you are making a breaking change might fit here is:

```
type ContextService interface {
  Serve(context.Context)
}
```

which is a service without a Stop(), that keeps running as long as the context is not done.
Service termination effectively closes the context.

This way we can nicely propagate the context down to other APIs, which all nicely unwinds when the service is instructed to stop.
Given a lot of the go standard library now propagates the context, this fits in nicely and results in very well defined lifetimes of the service which have very responsive terminations. 

It also fixed a very very large source of bugs for us, where we'd have things/services restart in quick succession, effectively call stop a second time before the first stop returned, bulldozing our own internal state on the service causing panics.

This is because there is no common entry point between start and stop, the state to signal the transition from running to stopping usually becomes some sort of instance variable on the service struct (a channel or what not).

**Comment by AudriusButkevicius** [comment]
Another logical extension might be to provide a way to hook into the errors returned by the services in the supervisor, for logging purposes if anything else.

I guess it would also make sense to update the default termination reason message to encapsulate the error if it was not nil.
I know I abused panics just to get a message to failure reports, as to me it felt error/state reporting was the supervisors job, not the services.

**Comment by thejerf** [comment]
I was definitely going to put the errors in the log.

I had been reluctant to put contexts on the services in suture on the grounds that I haven't found a design that A: conforms to the general specs given in the context document and B: isn't subject to a lot of misuse. For A, the part that bites in particular is that I really need to stick them in my structs. Now, I'm not going to cry too hard if we break that rule, but it is something I've been looking out for.

It seems like what we'd need is to put a context.Context on a supervisor at creation time, then pass the supervisor's context down to the service. I get hung up a bit then in that if you add a supervisor to the tree, it could have both its own context and the context passed to it. I suppose if I'm biting the bullet and going for a new major version, one option is to make it so supervisors aren't Services anymore, so the aforementioned issue can't happen anymore. You can build a tree, but you have to ask for "sub supervisors" from an explicit method call on the supervisor; supervisors would no longer be something you can add to supervisors. (In this case, the sub-supervisor would get its own context via a WithCancel.

I'm definitely open to this sort of conversation. In some ways if we're going to roll a major version, I'd rather it was worthwhile. Context integration is definitely up there on the list.

Probably arrange things to be context-centric first, with a defined, prepared mechanism for creating a non-context-based service. (I have a couple of things that still involve things that can't use contexts.)

**Comment by AudriusButkevicius** [comment]
Supervisors are still services. The user would have call the first/root supervisor with a user created context, and store it's cancellation function somewhere, if he ever decides to terminate the supervisor. I don't think I'd store it on the body of the supervisor, because if let's say you stop and want to start the supervisor again (is this even a supported scenario for services or supervisors?), you'd have to reassign a new context. Also, I guess public member variables are mutable, and you don't want that.
I guess you could require it to be passed in the config, but still not sure it's worth it.

In terms of storage, the only thing that changes is that instead of looking up the service reference and calling stop on it (for a given service token), you look up the cancellation function for the service and call that. I guess you still want to store a service reference and the cancellation function for the purpose of getting the name of the service and what not.

Then in theory, if the contexts that are given to the services are child contexts of supervisor, then calling the cancel function of the supervisor context should be enough to cancel everything. In practice I individual service specific cancellations should still be called, and perhaps there is even reasons not to make the service contexts children of the supervisor context.

You can see our wrapping around it in: 
https://github.com/syncthing/syncthing/blob/main/lib/util/utils.go#L234

**Comment by thejerf** [comment]
> In practice I individual service specific cancellations should still be called, and perhaps there is even reasons not to make the service contexts children of the supervisor context.

Part of the "supervision tree" idea is that you can indeed have a tree, and potentially shut down and/or restart just a branch of it, or have different policies on different portions of it. You'd need child contexts on the sub-supervisors to accomplish that. It's a common use case to have just one supervisor with one policy, but definitely not the only policy.

That wrapper is exactly the sort of thing I was thinking of, yeah.

> Supervisors are still services

When I say they aren't services, I mean they may no longer conform to the Service interface. This is because if you have a Supervisor in your hand that you're going to make a child of another supervisor, then there's a problem with the fact the new child should have a subcontext of the parent, but you may also have assigned your own context to it. Were those mergable we wouldn't have a  problem, but they aren't.

Given that I already have a case where a parent supervisor will penetrate the Service abstraction to do some fiddling with log handling, possibly the design that's trying to get out here is a reification of the supervisor tree itself as a top-level object, where you configure logging policy and other shared things like that, then start asking for Supervisors from that. Supervisors could still request sub-supervisors. The individual supervisors would then have settings on them that make sense for that specific supervisor, like restart policy. Requesting a supervisor would come with its individualized cancel function if you want it, and you'd pass the supervisor a top-level context to be shared with everything, which could also be cancelled.

Does syncthing have services that get restarted, and services that should trigger a full-program shutdown if they fail?

**Comment by AudriusButkevicius** [comment]
> there's a problem with the fact the new child should have a subcontext of the parent

If you go with the approach where context is passed into serve (of the service as well as the supervisor), then this is not a problem and no magic is required as you don't need to reach in anywhere anymore.


We definately have services that should trigger shutdown of the whole application if they fail. 
For example service for connections, if we can't accept any connections, the application can't function. Restarting the service with backoff is unlikely to help, especially if we know the error is fatal, due to the port being taken or something alike.


It's hard to say whether we have services that restart, given how we've wrapped everything now, but I think we just terminate serve to trigger a restart by the supervisor. I don't think we explicitly do RemoveAndWait/Add again.

**Comment by thejerf** [comment]
>If you go with the approach where context is passed into serve (of the service as well as the supervisor), then this is not a problem and no magic is required as you don't need to reach in anywhere anymore.

Right, thank you. That makes sense. We can put a context on the top-level supervisor tree object. For _all_ services, when adding, the supervisor you add it to will create a new cancellation context for it, and return the cancel method, which you can grab if you want it. A lot of the time, you won't care, but if you want to kill a supervisor tree you can keep that one. Supervisors are Services and they get created via a function that does things like configure how murderous they are if there's a service failure.

> It's hard to say whether we have services that restart, given how we've wrapped everything now,

I think we can fix that up too. What we're talking about here should clean the code up anyhow:

```
supervisorTree := NewTree(...)
killOnRestart := NewSupervisor(supervisorTree, PropogateFailure, ...)
justRestart := NewSupervisor(supervisorTree, Restart, ...)

// Things added here shut down the entire program if they fail
killOnRestart.Add(...)

// Things added here get restarted without killing everything
justRestart.Add(...)
```

API still in progress. These are very raw thoughts. There isn't much point to free-floating supervisors, so the NewSupervisor (or possibly just New) could take a parent argument, to prevent you from failing to add it to a parent, since that's just going to be an error. Prevents multiply-adding a supervisor accidentally, too.

I've been tempted for a while to add a method that prints out the supervision tree for exactly that sort of debugging question. It's the reason why the original API wants you to give everything a "human name"; it's in prep for this feature. It looks like we might be ending up with a cleaner data structure to run that against here.

**Comment by AudriusButkevicius** [comment]
I am not sure I follow what the tree structure is for, as in my head the only API change that needs to happen is
```
type Service interface {
   Serve()
   Stop()
}
```

becomes
```
type Service interface { 
    Serve(context.Context) error
}
```

then stuff like this before:
```
main := NewSupervisor(cfg)

connectionTree = NewSupervisor(connectionCfg)
database = NewSupervisor(databaseCfg)

connectionTree.Add(serviceThatWillReturnPropogateFailure)


connectionToken := main.Add(connectionTree)
databaseToken := main.Add(database)

ctx, cancel := context.WithCancel(context.Background())
defer cancel()
err := main.Serve(ctx)
if errors.Is(err, suture.PropogateFailure) {
    os.Exit(1)
}
```

still works, and PropagateFailure is signaled by the return value of the service (which if of type PropogateFailure, the supervisor shuts everything down, and bubbles the same error up to whoever called it's serve, and restarts the service in all other cases) 

PropogateFailure is probably a bad name for an error, but something along the lines of a fatal error.

**Comment by thejerf** [comment]
Yeah, that makes sense.

Like I said, very raw thoughts here. My brain is primarily tasked on my normal workday job here right now. :) I think you're right about the API.

I think the NewSupervisor needs a parameter for how it handles failure. When it receives the error from the service, you need to be able to control whether it's going to eat it or propagate it up. It may not be a usecase syncthing is interested in, but it is one someone will need.

**Comment by AudriusButkevicius** [comment]
Why can't that be controlled by checking the type of error returned?

Seems like a much cleaner API, and less things to store 🙃

**Comment by thejerf** [comment]
When a supervisor is getting terminated and has to return an error to _it's_ supervisor, that code is going to live in suture. Both telling its parent supervisor to die, and telling its parent supervisor "hey, I'm dead now, don't restart me, but don't die yourself" is sensible. You can't change the supervisor's code that does that.

Though now that I type that out, I'm not sure how sensible that is. I'm having trouble coming up with an example of a supervisor sub-tree in a long running program that we're ok with just dying. Although if you set up your logging code correctly, you could observe this and then do something in response. (Although you'd think just about the only sensible thing to do would be to restart it, which is better done via, you know, letting things restart.) My inability to come up with the case off the top of my head doesn't mean there isn't one... but maybe there isn't.

Well... maybe the way to go is to just let it propagate for now. Since the New call already accepts a struct, adding a parameter later to eat the error for that supervisor instead of propagating it is backwards compatible.

**Comment by AudriusButkevicius** [comment]
So I started implementing this and I came to a small problem.

Stop() is currently supposed to block until the Serve() loop has finished processing the requests.

This can't be easily replicated with a context, because cancellation function simply closes the channel, it doesn't know if the closure of the channel was observed by Serve or not, making a lot of tests fail.

I came up with a small wrapper around the cancellation function which effectively blocks and waits for Serve() to return.

This seems to break things like: TestStopAfterRemoveAndWait which tries to get the service into a specific spot but doesn't let it return.

Any thoughts about this?

**Comment by thejerf** [comment]
I think the core goal is the Supervisors should be done stopping until their children are done. I'm less worried about the .Stop() methods on services being synchronous themselves. Supervisors could be switched to looking for their service's Serve methods having returned.

With that requirement, you really could get rid of Stop being required on services. Make them 100% context based and have a backwards-compatible wrapper for the older style.

**Comment by AudriusButkevicius** [comment]
I've raised https://github.com/thejerf/suture/pull/40 which fails on some tests, yet I am not sure I understand the tests.
The very basic one is TestCompleteJob where the tests hangs on reading from stop, yet I can only see anything being sent to that channel after termination, yet termination happens after reading from stop, so I am a bit at a loss of how that worked before.

Haven't looked at other tests.

**Comment by thejerf** [comment]
The tests are pretty twisty and deeply integrated into the gory guts of the insides, which, given the type of code we're talking about, is probably an OK and justified thing, but... don't try to hard to disentangle them. I expect this is going to be one of the rare cases where I may end up nearly burning them down. Putting synchronization checks into what are putatively logging functions is among the most evil test cases I've ever written.

Mostly I'm hoping to salvage the core supervisor loop with minimal changes, on the ground that at this point it's fairly well tested.

I'm tentatively planning on putting some serious time in to this this weekend. I don't think I can promise it'll be done by then, but there will probably at least be something to look at. I'll have a good look at your PR as well.

**Comment by AudriusButkevicius** [comment]
So the PR I've opened now passes all tests, with a workaround for all tests that use UseStopChan, as well as a suspicious fix to TestCompleteJob.

I guess if you feel my PR won't cut it, and you want to on the adventure differently, I guess it could atleast be used to describe the API I was talking about.

If you think my PR is workable, I guess I could add tests for the new components/paths I am adding.

**Comment by thejerf** [comment]
I'll have a look this weekend. I expect I'll start with your PR, but whether it looks like it by the end.. well... who knows? I may try to unsnarl some things that are getting a bit snarled in the tests. I'll credit you in the README regardless. (I should already have a section there and I don't. If I forget this, please call me on it.)

While we're having a frank discussion with what is probably my biggest user, how do you feel about the logging closures? I've never liked the way they work, but I feel like there's a lot of reason to ensure the users are getting structured messages, and I don't know any other reliable way to structure them for people. (At least, not one that's fundamentally different. In hindsight, I should have emitted structs so I could add fields without breaking compatibility. I'm tempted to do that on a major release...) I really don't want to lock people into parsing some sort of string output. I still don't have anything better but I'm open to ideas.

I suppose I could take a single Log(interface{}) (or a tiny interface declared just for the logging messages, if that makes people feel better) and push a defined set of structs through that, instead of taking so many distinct kinds of closures.

**Comment by AudriusButkevicius** [comment]
I don't think we rely on the logging stuff heavily, so honestly I don't think we care much.
I think we simply set the Log function that goes through our loggers to respect the levels and that's it. 


Looking at the logging as it is the following comes to my mind, this is just my uneducated observations of what I'd change:

Backoff:
The backoff stuff could be replaced with a strategy, hence users can choose if when and for how long to back off. Perhaps after 10 times, you want the supervisor to give up and tear itself down (by returning some magical error in theme with the Serve() error stuff which might take the whole application down).  I'm not sure we need it, so perhaps it's a YAGNI (urban dictionary) for others too.

You could have the existing backoff strategy as an implementation for that interface, where by users can set OnEnteringBackoff OnLeavingBackoff function pointers to be notifier as this stuff happens (outside of the interface I guess), so users can choose to log. If they are not using the default implementation, I don't think there is any point to force logging. They will know when things are going into backoff based on what they are returning from the strategy.

I don't think it's sensible for any libraries to log stuff by default, because libraries have no clue what logging framework the application is using, so they should be silent by default.

Also, current naming has Logger in everything, where in reality it's not really logging as in outputting text, there are more like notification hooks.

LogBadStop:

Again bad name, this logs by default but is more of a hook. I suspect OnStopTimeout would be better, because that's the only condition that can log a bad stop. I am not sure if it's worth passing the service name, as it most likely has no meaning to the user, given at best it's fmt.Stringer which the user can assert/evaluate himself, at worst, some internal format the library decided that has no meaning outside of the libraries realm. The user probably knows better how to turn a Service interface into something he can get a meaningful name for.

LogFailure

This one is a bit of a catch-all thing. 
Perhaps this should be separated into OnServicePanic OnServiceFailed, so that in case of a simple Serve returning you don't have to figure out whether it's a panic or not.
Setting/Not setting OnServicePanic could also be a good replacement for the PassThroughPanics flag.

I guess this is contraversial opinion, but I'd leave OnServicePanic unset out of the box, and by default propagate panics.
Panics are usually bad off by one bugs or sends on closed channel, where retrying either doesn't help or masks a genuine logic error.

For OnServiceFailed, I guess you would want to log something by default here, as silently retrying services is a bit grim and if silent by default even with good documentation users might be confused.

Not sure how I'd do that, perhaps have suture.New return an error, where if OnServiceFailed handler is not set it returns an error, and then have suture.NoopServiceFailureHandler and suture.LoggingServiceFailureHandler(func(string))

I guess getting the service token on service failure would be useful, in case the users decides to remove the service from the supervisor, likewise for the panic. Again, not sure how useful the name is.

**Comment by thejerf** [comment]
I think based on that, I'll target the original minimal API change. I'm building on your branch, but I'm starting with some refactoring work just to clear away some of the messiness suture has accumulated so I can see a bit more clearly to the underlying code.

However, there are some API changes I'm making:

  * I think Stop is going to go away on the supervisor. The way to stop it is to cancel its context. The UnstoppedServiceReport (which is from another request) will be generated at shutdown and available via a method call. Having two ways to stop the supervisor is both confusing and internally dangerous to code.
  * I set ServeBackground to take a context too.

What kind of timeframe are you looking at for this to be done? If you need this right away, I can push it somewhere for you to try out the API, but I am currently not guaranteeing that it works while I tear through it. If you don't need it right away I'd rather finish propagating the changes and hand you something that, while I still may not fully "guarantee", I can at least _claim_ is likely to work. :) I'd be looking at next weekend for that, I think.

**Comment by AudriusButkevicius** [comment]
Regarding the API, probably your suggestion is better but I was thinking that in case of unstopped services, the supervisors Serve could return a special error, where you could do:
```
err:= supervisor.Serve(...)

var unstoppedErr *UnstoppedServicesError
if errors.As(err, unstoppedErr) { 
     println(unstoppedErr.UnstoppedServices())
}
```

Which could also satisfy ErrComplete.

In case of all services stopping fine, it would return nil.

Regarding the timelines, I guess once the API is settled, we could start conversions on our side, while you iron out the implementation.

**Comment by thejerf** [comment]
My intuition is telling me that the unstopped service report isn't really an "error". We've kind of already crossed that line with ErrComplete & ErrTerminate, but I'm really not sure I like a complex error that matches both ErrComplete & also has details inside of it about services that didn't stop. If nothing else, that feels like having packed two errors into one... which also isn't necessarily a terrible thing, I've done it before in my real code, but it still seems like not something I should do on purpose.

But logically, what you posted works.

Well, I guess I'll just start working with this and see if anything jumps out as I go. Sometimes these things end up telling you what they want as you go.

**Comment by AudriusButkevicius** [comment]
So I proposed that because that was the first thing that came to my mind when I was thinking of how to remove the StopWithReport method.

I guess I'd prefer having a separate method, as it's less magical., though you need to handle it being called before the supervisor is stopped.

I have not checked how it works, but I guess these things do not chain the reports across tree do they?

As in, if I have supervisors A B C.
A runs B and services, B runs C and some services, C runs some services.

I stop A, will I get report for C's and Bs services that failed to stop (the whole tree) or just A?

**Comment by thejerf** [comment]
>though you need to handle it being called before the supervisor is stopped.

Yes, there is some internal state that can be used to track this. It looks like the current implementation defined a "terminated" state but never transitioned to it... that's easy to fix. (Didn't hurt anything since this was entirely an internal thing.)

> I have not checked how it works, but I guess these things do not chain the reports across tree do they?

Sigh... no, they do not. I was noticing that as I was in there fiddling around. I believe the person who wanted that was probably not using nested supervisors so they did not care. But, yeah, I ought to fix that while I'm in there, because it ought to cover the whole tree.

**Comment by AudriusButkevicius** [comment]
I am pretty sure it's us who wanted that, was we had problems not knowing what's preventing shutdown.

**Comment by imsodin** [comment]
Regarding timeframe: I would start working on the Syncthing side of things as soon as you consider an API likely to not change anymore, regardless of whether it works at all (I'll create a stub if neccesary). Switching existing services over to the new api is mostly dump leg-work, but it's a requirement to bring sensible failure handling to our db handling. And I would like to get that sensible db handling :)  
So no need to hurry - a heads-up once you (more or less) settle on a design would be appreciated.

**Comment by thejerf** [comment]
I think what is on my `jcontext` branch is at least getting close. Note there's some changes around the semantics of the UnstoppedServiceReport. It probably matches the way you're already using it, but I should point it out. Renamed the errors, too. When I get the errors into the log I will probably change the error text to look good in a log message but that's not a huge change.

I'm not 100% sure about the logging interface. I haven't analyzed them to see if they ought to grow a parameter to indicate if they service asked to be shut down or terminate the tree yet. But I think the impact of this is likely to be minimal on you, you probably set it up in one place.

I don't even know if that code compiles, I'm still working on it, but I think the the interface should be fairly stable. Also I don't guarantee the documentation has all been harmonized yet.

(I've been working on propagating the changes. For instance, the old supervisor had a "liveness" channel built into it that was essentially functioning like a context's Done channel, which is now redundant to the context's Done channel. Working on some cleanup and such before I start into the testing.)

**Comment by imsodin** [comment]
Sounds good. Looking at it a few questions/comments came to mind. Easiest way to address/discuss them would be code comments. Could you file a wip PR for the jcontext branch for that?

As Audrius wrote before: We don't do much with the logging interface, so that's not a priority to us (though we definitely could, and probably should, improve that).

**Comment by imsodin** [comment]
> I also have some plans on how to get the unstopped service report to work with the entire supervision tree. That's the cause of the changed semantics on that call, and if you look, while it doesn't do anything yet and may well be one of the things that doesn't compile yet, the report now has a field for indicating the supervisor tree path to the service that didn't stop.

I just realized the way we are using supervisors is incompatible with that: We embed supervisors into a struct, sometimes even overriding/extending methods like `Serve`, and pass that to `.Add`. That works just fine for the main functionality, but stuff like propagating logging funcs and a future supervision tree wont, at least not with the current `.(*Supervisor)` type assertion. That could be solved by making `Supervisor` an interface, in which case the assertion on an embedded struct would work.

**Comment by thejerf** [comment]
> That could be solved by making Supervisor an interface, in which case the assertion on an embedded struct would work. Or alternatively add an interface with .IsSupervisor() (*Supervisor, bool) that a type embedding a supervisor can implement. This won't allow for overloading, but that's probably a bad idea anyway.

If I'm going that route, then I'll extract out the log setting as a method that is part of the interface, and then anything can implement it.

I've been on vacation the past four days. I've pushed the WIP to jcontext, but bear in mind it's a total WIP, it doesn't even compile at the moment. I'm propagating a lot of changes through to match the underlying implemantation to the new interfaces.

**Comment by thejerf** [comment]
I have pushed a new version of my "jcontext" branch that _should_ recover the original functionality of suture with the new context stuff. However, it does not yet have testing around the new errors. I'm also going to be testing what happens if you get errors from the context (deadline exceeded, etc.) and do my best not to restart services just for them to be torn down immediately again, and any other corner cases I can think of. So there could still be some funkiness in the teardown procedures from cancelling a context or handling around the new errors. There's a few other aspects I'm going to be adding testing for too.

**Comment by imsodin** [comment]
I implemented v4 on Syncthing https://github.com/syncthing/syncthing/pull/6947 and it seems to basically work. Work as in it runs and shutdown initiated by a service through the new termination error actually does terminate the entire tree - there's not much if any testing of suture in our test suit.

**Comment by thejerf** [comment]
That is good to know, thanks. It's still my next copious-spare-time project to finish up the testing.

Testing suture has always been a challenge, but I have to adit I'm really blanking on how to test that a service does NOT restart. :)

I've considered maintaining v3 going forward, yes. For instance, it could really use the fix to crawl the whole supervisor tree for the stopped service report. I don't think I'll port new features to it, but I might bugfix it. If nothing else, I personally still have a lot of code that's on v1-v3.

**Comment by thejerf** [comment]
As the event log shows, I've merged & modified @imsodin's event hook work. Tomorrow I'm going to take a last pass at the docs, including the new comments... and then I need to stare at the TravisCI results, which is claiming this branch is failing to test fairly consistently, despite the fact it's looking fine on my machines (and, I presume, yours).

I'm basically out of wish list items; anyone else? :)

**Comment by imsodin** [comment]
> and then I need to stare at the TravisCI results, which is claiming this branch is failing to test fairly consistently, despite the fact it's looking fine on my machines (and, I presume, yours).

The test failures are legitimate: I have been super sloppy "backporting" my changes to `Add` to non-v4. Fix: https://github.com/thejerf/suture/pull/46

> I'm basically out of wish list items; anyone else? :)

Apart from the above, my only remaining wish is a release tag :)

**Comment by imsodin** [comment]
Hmm, still open - I hope it's ok if I do the honours :)

Thanks again @thejerf for all of this!

Fixed by https://github.com/thejerf/suture/pull/43
