### ISSUE TITLE
Configurable stop timeouts

### ISSUE THREAD

**Issue by d3xf** [thejerf/suture#8]
Would you consider making stop timeouts configurable instead of hardcoding them to 10 seconds (suture.go:523)?  The time required to stop a service can vary quite a bit.

Thanks for your work, suture is a great tool!

**Comment by thejerf** [comment]
Since you've encountered this use case and I have not, let me ask you: Do you need different timeouts per service, or do you want to configure it per supervisor (bearing in mind that we can easily use multiple supervisors)? I somewhat prefer the latter for code simplicity and I think no loss of generality, but, well, step 1, "Gather Requirements", right?

**Comment by d3xf** [comment]
I agree, I don't see a need at the moment for per-service stop timeouts as the supervisor timeout can just be set to `max {stop_timeout(s) : all services s}`.

On a slightly different note, it would also probably be useful to be able to supply a hook to call in the event of a timeout so that steps other than printing a log message can be taken.

**Comment by thejerf** [comment]
Well... don't tell anyone, but... since you can specify the log procedure as a function, you can do whatever you want with that. However, I should warn you that during testing I found that that is quite fragile if you do anything that could interfere with suture itself, which isn't a surprise due to the way multithreading stuff works. It's pretty important that whatever the function does, there isn't any way for it to end up reaching back out to a lock indirectly held by suture or any children. But that does leave a wide range of possible options.

I'm going to close this issue for cleanliness. If my previous paragraph does not satisfy you, please open another one for a hook on shutdown.
