### ISSUE TITLE
Cross service dependencies (like links and monitors in Erlang)

### ISSUE THREAD

**Issue by fuson** [thejerf/suture#9]
All in topic :)

**Comment by thejerf** [comment]
See [reign](https://github.com/thejerf/reign).

Note that the semantics come out different since you can't actually kill a goroutine, but it still has many similarities.

Also, while I promise nothing, work has resumed on that repo, there's just nothing public yet. But we've got a guy at work now who is fixing this up as of this week, and making good progress.
